version: "3.8"
services:
  db:
    image: postgres:16.2-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "8001:5432"